services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: app-many-backends-laravel-nginx
        ports:
            - "3111:80"
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service

    # php
    php82-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: app-many-backends-laravel-php
        ports:
            - "3112:9000"
        volumes:
            - ./:/var/www/project